### ISSUE TITLE
Error: manifest not found

### ISSUE THREAD

**Issue by mbanon** [HazyResearch/meerkat#356]
**Describe the bug**
I tried to run the meerkat demos in a fresh python3.10 environment. Some of them fails with  "ModuleNotFoundError: No module named 'manifest`".

**To Reproduce**
Run:
```
python3.10 -m pip install meerkat-ml
mk -demo chatgpt
```
And you get:

```
Traceback (most recent call last):
  File "/home/motagirl2/venvs/py-mk/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/motagirl2/venvs/py-mk/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/motagirl2/venvs/py-mk/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/motagirl2/venvs/py-mk/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/motagirl2/venvs/py-mk/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/motagirl2/venvs/py-mk/lib/python3.10/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/motagirl2/venvs/py-mk/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/motagirl2/venvs/py-mk/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/motagirl2/venvs/py-mk/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/motagirl2/venvs/py-mk/lib/python3.10/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/motagirl2/venvs/py-mk/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/motagirl2/venvs/py-mk/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/motagirl2/venvs/py-mk/lib/python3.10/site-packages/meerkat-demo/chatgpt.py", line 14, in <module>
    from manifest import Manifest
ModuleNotFoundError: No module named 'manifest'
```

**Expected behavior**
I would expect the demo not to crash :)

**System Information**
 - OS: Ubuntu 22.04.2 LTS
 - Versions for RG and relevant dependencies: Python 3.10.6,  meerkat-ml==0.4.9

**Comment by seyuboglu** [comment]
Hi @mbanon - this demo relies on an external library called [Manifest](https://github.com/HazyResearch/manifest). You can install it with `pip install manifest-ml`
