### ISSUE TITLE
[BUG] ImportError: cannot import name 'StringMethods' from 'pandas.core.strings'

### ISSUE THREAD

**Issue by gkiril** [HazyResearch/meerkat#371]
**Describe the bug**
When I try to import DataPanel from meerkat with:

`from meerkat import DataPanel
`
I get the following error:

`ImportError: cannot import name 'StringMethods' from 'pandas.core.strings'
`
**To Reproduce**
Steps and code snippet that reproduce the behavior:

1. Code snippet: `from meerkat import DataPanel`
2. Instructions (Run '...'): run this simple script with the import. The same happens when I try to import meerkat in general: 
`import meerkat`
4. Errors and traceback:

```
Traceback (most recent call last):
  File "c:\workspace\summvis\summvis.py", line 11, in <module>
    from meerkat import DataPanel
  File "C:\Users\user\AppData\Local\anaconda3\envs\summvis_venv2\lib\site-packages\meerkat\__init__.py", line 12, in <module>
    from meerkat.columns.audio_column import AudioColumn
  File "C:\Users\user\AppData\Local\anaconda3\envs\summvis_venv2\lib\site-packages\meerkat\columns\audio_column.py", line 7, in <module>
    from .file_column import FileColumn
  File "C:\Users\user\AppData\Local\anaconda3\envs\summvis_venv2\lib\site-packages\meerkat\columns\file_column.py", line 12, in <module>
    from meerkat.columns.pandas_column import PandasSeriesColumn
  File "C:\Users\user\AppData\Local\anaconda3\envs\summvis_venv2\lib\site-packages\meerkat\columns\pandas_column.py", line 29, in <module>
    from pandas.core.strings import StringMethods
ImportError: cannot import name 'StringMethods' from 'pandas.core.strings' (C:\Users\user\AppData\Local\anaconda3\envs\summvis_venv2\lib\site-packages\pandas\core\strings\__init__.py)
```

Include any relevant screenshots.

**Expected behavior**
This should not raise exceptions

**System Information**
 - OS: Windows
 - Versions for RG and relevant dependencies: `meerkat-ml` (v0.2.4)

**Comment by gkiril** [comment]
Solved this by downgrading pandas to 1.4.1
